apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: iftar-job
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: iftar-job
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - image: mabdi05/maghrib-notifier:latest
            name: iftar-job
            resources: {}
          restartPolicy: OnFailure
  schedule: 0 17 * * *
status: {}
