apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: argo-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: argocd-test.com
    http:
      paths:
      - backend:
          service:
            name: argocd-server
            port:
              number: 443
        path: /
        pathType: Prefix
status:
  loadBalancer: {}
