apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: logging
  name: logging
spec:
  containers:
  - image: mabdi05/log-generator:latest
    name: logging
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
# pod will fail since the hosted docker image is private
# please revert the changes in docker if want this pod to work. 