apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mongo-express
  name: mongo-express
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mongo-express
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongo-express
    spec:
      containers:
      - image: mongo-express
        name: mongo-express
        ports:
        - containerPort: 8081
        resources: {}
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom: 
            secretKeyRef:
              key: USERNAME
              name: mongo-secret
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom: 
            secretKeyRef:
              key: PASSWORD
              name: mongo-secret
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom: 
            configMapKeyRef:
              key: database_url
              name: mongo-config
        volumeMounts:
        - name: vol 
          mountPath: /var/configs/express-logs 
      volumes:
      - name: vol 
        persistentVolumeReclaimPolicy:
          claimName: mongo-pvclaim 
status: {}
