apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: myjob
spec:
  completions: 3 
  parallelism: 3 
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - command: ['expr', '3', '+', '2']
        image: busybox
        name: myjob
        resources: {}
      restartPolicy: Never
status: {}

---
