apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: db
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: bk
    ports:
    - protocol: TCP
      port: 80
  - from:
    - podSelector:
        matchLabels:
          app: ft
    ports:
    - protocol: TCP
      port: 80

  egress:
  - to:
    - podSelector:
        matchLabels:
          app: bk
    ports:
    - protocol: TCP
      port: 80

# backend pod manifest:
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: bk
  name: backend
spec:
  containers:
  - image: nginx
    name: backend
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

# frontend pod manifest:
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: ft
  name: frontend
spec:
  containers:
  - image: nginx
    name: frontend
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

# database pod manifest:
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: db
  name: db
spec:
  containers:
  - image: nginx
    name: db
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}