apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: my-job
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: my-job
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - image: busybox
            name: my-job
            command: ['expr', '3', '+', '2']
            resources: {}
          restartPolicy: Never
  schedule: '0 0 1 * *'
status: {}


